from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from .errors import GuardedOpsError


def load_route_config(path: str | Path) -> dict[str, Any]:
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise GuardedOpsError("route config must be a JSON object")
    if "targets" not in data or not isinstance(data["targets"], dict):
        raise GuardedOpsError("route config must contain targets")
    return data


def emit(payload: dict[str, Any]) -> int:
    print(json.dumps(payload, indent=2, sort_keys=True))
    return 0


def cmd_doctor(args: argparse.Namespace) -> int:
    config = load_route_config(args.config)
    return emit(
        {
            "status": "ok",
            "mode": "synthetic",
            "targets": sorted(config["targets"]),
            "sources": sorted((config.get("sources") or {}).keys()),
        }
    )


def cmd_preflight(args: argparse.Namespace) -> int:
    config = load_route_config(args.config)
    target = config["targets"].get(args.target)
    if not target:
        raise GuardedOpsError(f"unknown route target: {args.target}")
    return emit({"status": "ok", "target": args.target, "host": target.get("host"), "port": target.get("port", 22), "network": "not-executed"})


def cmd_proxycommand(args: argparse.Namespace) -> int:
    config = load_route_config(args.config)
    target = config["targets"].get(args.target)
    if not target:
        raise GuardedOpsError(f"unknown route target: {args.target}")
    command = ["nc", str(target.get("host")), str(target.get("port", 22))]
    if args.print_json:
        return emit({"command": command})
    print(" ".join(command))
    return 0


def cmd_sync_ssh_config(args: argparse.Namespace) -> int:
    config = load_route_config(args.config)
    output = Path(args.output)
    lines = [
        "# Generated by GuardedOps routectl",
        "# Synthetic example only.",
        "",
    ]
    for name, target in sorted(config["targets"].items()):
        lines.extend(
            [
                f"Host {name}",
                f"  HostName {target.get('host')}",
                f"  Port {target.get('port', 22)}",
                f"  ProxyCommand routectl proxycommand --target {name}",
                "",
            ]
        )
    rendered = "\n".join(lines)
    if args.dry_run:
        print(rendered)
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    return emit({"status": "ok", "output": str(output), "hosts": sorted(config["targets"])})


def cmd_git(args: argparse.Namespace) -> int:
    config = load_route_config(args.config)
    git_host = config.get("git_host", "git.example.com")
    return emit({"status": "dry-run", "git_host": git_host, "operation": args.operation, "route_source": args.source})


def cmd_acceptance(args: argparse.Namespace) -> int:
    config = load_route_config(args.config)
    return emit(
        {
            "status": "ok",
            "plain_ssh_targets": sorted(config["targets"]),
            "git_host": config.get("git_host", "git.example.com"),
            "network": "not-executed",
        }
    )


def cmd_run(args: argparse.Namespace) -> int:
    load_route_config(args.config)
    return emit({"status": "dry-run", "region": args.region, "command": args.command})


def cmd_matrix(args: argparse.Namespace) -> int:
    load_route_config(args.config)
    regions = [item.strip() for item in args.regions.split(",") if item.strip()]
    return emit({"status": "dry-run", "regions": regions, "command": args.command})


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="routectl")
    parser.add_argument("--config", default=str(Path("examples") / "route.example.json"))
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("doctor").set_defaults(func=cmd_doctor)
    preflight = sub.add_parser("preflight")
    preflight.add_argument("--target", required=True)
    preflight.set_defaults(func=cmd_preflight)
    proxy = sub.add_parser("proxycommand")
    proxy.add_argument("--target", required=True)
    proxy.add_argument("--print-json", action="store_true")
    proxy.set_defaults(func=cmd_proxycommand)
    sync = sub.add_parser("sync-ssh-config")
    sync.add_argument("--output", required=True)
    sync.add_argument("--dry-run", action="store_true")
    sync.set_defaults(func=cmd_sync_ssh_config)
    git = sub.add_parser("git")
    git.add_argument("--operation", default="ls-remote")
    git.add_argument("--source", default="default")
    git.set_defaults(func=cmd_git)
    sub.add_parser("acceptance").set_defaults(func=cmd_acceptance)
    run = sub.add_parser("run")
    run.add_argument("--region", required=True)
    run.add_argument("command", nargs=argparse.REMAINDER)
    run.set_defaults(func=cmd_run)
    matrix = sub.add_parser("matrix")
    matrix.add_argument("--regions", required=True)
    matrix.add_argument("command", nargs=argparse.REMAINDER)
    matrix.set_defaults(func=cmd_matrix)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except GuardedOpsError as exc:
        print(f"routectl: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
